export {default as Home} from './home'
export {default as Browse} from './browse'
export {default as Signin} from './signin'
export {default as Signup} from './signup'
export {default as Contact} from './contact'
export {default as Politique} from './conditions'